- ros_topic_name: /camera/image
  gz_topic_name: /world/aerointercept_park/model/x500_depth_1/link/camera_link/sensor/IMX214/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
